[package]
name = "rando"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "0.12.4"
hashbrown = "0.1.2"
glob = "0.3.1"
ips = "0.1.0"